### PR TITLE
pool auto-importer for macOS 10.15 and 11

### PR DESCRIPTION
**Pull request by glessard**
### Motivation and Context
This adds a new pool importer tool for macOS to replace the old `zpool-import-all` shell script. The replacement gets listed under its own name in the "Full Disk Access" portion of macOS's Security preference pane. The old script unfortunately required giving `bash` full disk access, which is an overly blunt tool.
I introduced the tool on the openzfsonosx forum:
[https://openzfsonosx.org/forum/viewtopic.php?f=24&t=3511#p10836](url)

### Description
Adds a new launchd plist under `etc/launchd/daemons`, and the new tool under `etc/launchd/launchd.d`.
The new tool is written in Swift and gets its parameters from the launchd invocation.

### How Has This Been Tested?
I have tested it under Big Sur (11.x) and Catalina (10.15.7). In both cases the replacement tool successfully imported the pools at startup, as expected.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by glessard** [comment]
I opened a PR to get comments and some pointers. I don't have the makefile.am for the zfs-pool-importer tool yet, since I haven't written a makefile of any sort it about 15 years. Otherwise, does this pass muster? Did I target the right branch? Thanks!

**Comment by lundman** [comment]
Sorry for the delay, I totally don't see PRs being made :)

I can't comment on the swift code, but the rest seems reasonable. You probably should do Makefile.am instead of install.sh, and handle things in there. You can see path.d/Makefile.am for a simple version that pretty much does nothing but install.

**Comment by glessard** [comment]
@lundman on branch `macOS` the `./configure` script fails to complete; this makes testing my makefile impossible unfortunately. `configure` stops on a missing `Makefile.in`. I thought the sequence should be:

$ aclocal
$ automake
$ autoconf
$ ./configure

(I'm actually doing `./configure CPPFLAGS="-I/usr/local/opt/gettext/include -I/usr/local/opt/openssl/include" LDFLAGS="-L/usr/local/opt/gettext/lib -L/usr/local/opt/openssl/lib" CFLAGS="-g -O0" --sysconfdir=/etc --localstatedir=/var --prefix=/usr/local --sbindir=/usr/local/bin`, basically what's at https://openzfsonosx.org/wiki/Install.)

What's missing, then? Thanks for the pointers.

**Comment by glessard** [comment]
After looking a bit too long at the automake documentation, I decided that it would be a better use of my time to just translate the program to Objective-C rather than trying to force automake to run swiftc. [Note that my testing so far indicates that it works just fine.]

So here added is an ObjC version, though I cannot fathom why automake ignores it. So much for efficiency.

**Comment by ilovezfs** [comment]
I think it may be a bit heavy handed to use Swift for this. Why not use https://github.com/neurobin/shc to compile the existing import shell script? Won't that let you avoid giving full disk access to bash @glessard?

**Comment by ilovezfs** [comment]
I'm not yet understanding why FDA is only needed in the launchd context.

@glessard did you manage to determine which line(s) in the original import script actually trigger the need for FDA when launchd runs the script? I think we've been assuming it's https://github.com/openzfsonosx/openzfs/blob/macOS/etc/launchd/launchd.d/zpool-import-all.sh.in#L35 but is that actually true?

Is this a problem that affects ALL shell scripts trying to run from launchd or is there something the import script specifically is doing? For example, I was wondering if the problem could be accessing /var/run from launchd context https://github.com/openzfsonosx/openzfs/blob/macOS/etc/launchd/launchd.d/zpool-import-all.sh.in#L6-L7

Or maybe it doesn't like that we run /usr/sbin/system_profiler or /bin/sync

The last comment in https://developer.apple.com/forums/thread/129215 makes me think it may be useful to determine exactly what in the script is causing the problem:

> 3. Regarding Full Disk Access. What are you trying to do here? Clearly it is something with zfs. But Full Disk Access, especially in this context, shouldn't be required. Full Disk Access, especially in a non-sandboxed, root context, only protects certain sensitive Apple directories and certain user directories. If you are mounting new zfs volumes, it shouldn't have anything to do with Full Disk Access.

It's quite strange that FDA apparently isn't needed once the user logs in.

**Comment by glessard** [comment]
> Why not use https://github.com/neurobin/shc to compile the existing import shell script?

That might work -- I wasn't aware of that tool. In any case, it depends on whether the project and/or packager would be willing to add that dependency. On the other hand, `swiftc` and `clang` are part of the macOS devtools, and versions compiled by those compilers already exist.

**Comment by glessard** [comment]
The tool that needs to be called in a full-disk-access context is indeed `zpool`; removing that call from my version also removes the trigger to add it to full-disk-access, so clearly that's the cause. The documentation is approximately nonexistent, but it seems that it's the calling context that needs to bestow the capability.

I don't know what the difference is after someone logs in; presumably the process that runs the UI session has somewhat elevated privileges for something. In any case, translating the script to Objective-C may not be the perfect solution, but it does solve the major UX issue surrounding pool importing at startup.

**Comment by glessard** [comment]
Note that it's not just the `launchctl` context that requires full disk access:
Another context where running `zpool` fails is in an SSH session from which full disk access has been removed. You can do that by unchecking `sshd-keygen-wrapper` from the Full Disk Access list; don't remove it from the list -- just leave it unchecked. Then, log in with `ssh -A localhost`, and in that context `zpool import -a` will fail to find anything. If you check it again then it will work in a new SSH session.

**Comment by glessard** [comment]
Note that the script that I'm trying to replace is rather weird, with all the timing dependencies and layers of callers. It could be advantageous to modify `InvariantDisks` to have it launch something once it's happy with the system state; it could also launch `system_profiler` itself. `InvariantDisks` could also prepare the way so that the whole thing could become less racy: if it created an enclosing directory for its marking file *before* launching the task that eventually runs `zpool`, we would be able to depend on `launchd`'s "QueueDirectories" feature.

**Comment by glessard** [comment]
Another command that needs full disk access in just about identical contexts as `zpool import` is `mount_apfs -s <some_snapshot>`. Every context I've tried where I can make `zpool import -a` work, `mount_apfs -s` also works. I don't know whether that elucidates anything at all.

**Comment by glessard** [comment]
@ilovezfs
Thanks for the link to the dev forum post (https://developer.apple.com/forums/thread/129215?answerId=406759022#406759022). That comment from John Daniel made me retry another tack, and I got it to work this time. See https://github.com/openzfsonosx/openzfs/pull/26. It's a pretty minor change that does the same thing as the tool I submitted in this PR.

@lundman I'm closing this PR in favor of https://github.com/openzfsonosx/openzfs/pull/26.

**Pull request closed without merging**
